// Generated by build.py. Edit tokens.json.
using System.Drawing;
namespace Jano.AppKit {
public static class Tokens {
public const string Version = "0.2.0";
public static readonly Color Background = Color.FromArgb(13,15,17);
public static readonly Color Panel = Color.FromArgb(21,24,27);
public static readonly Color Raised = Color.FromArgb(28,32,36);
public static readonly Color Input = Color.FromArgb(16,19,22);
public static readonly Color Text = Color.FromArgb(231,235,238);
public static readonly Color Muted = Color.FromArgb(154,165,175);
public static readonly Color Line = Color.FromArgb(52,60,67);
public static readonly Color Accent = Color.FromArgb(60,255,145);
public static readonly Color AccentInk = Color.FromArgb(8,27,17);
public static readonly Color Success = Color.FromArgb(118,221,162);
public static readonly Color Warning = Color.FromArgb(242,198,109);
public static readonly Color Error = Color.FromArgb(255,153,157);
public const int SpaceXs = 4;
public const int SpaceSm = 8;
public const int SpaceMd = 12;
public const int SpaceLg = 16;
public const int SpaceXl = 24;
public const int SpaceXxl = 32;
public const int RadiusControl = 5;
public const int RadiusPanel = 8;
public const int RadiusWindow = 10;
public const int SizeText = 13;
public const int SizeSmall = 12;
public const int SizeHeading = 22;
public const int SizeControl = 36;
public const int SizeTouch = 44;
public const int SizeCaption = 32;
public const int SizeSidebar = 192;
public const string UiFont = "Segoe UI";
}
}
