'use strict';
const $=id=>document.getElementById(id), core=window.EditCore;
let lang='de', requestId=0, media=[], videoAsset=null, segments=[], total=0, outputTime=0, playing=false, lastFrame=0, busy=false;
let intro='signal',outro='frame',mask=null,engineAvailable=false;
const pending=new Map(),visuals=new Map(),video=$('source-video'),canvas=$('preview'),ctx=canvas.getContext('2d');
const textIds=['headline','intro-copy','outro-copy','prompt','font','text-position','format','safe-preset','length','fit','safe-top','safe-right','safe-bottom','safe-left','music','sound','music-volume','sound-volume','original-volume'];
const T=(de,en)=>lang==='en'?en:de;
function notice(message,error=false){$('notice').hidden=false;$('notice').textContent=message;$('notice').classList.toggle('error',error);}
function api(op,args={}){return new Promise((resolve,reject)=>{if(!window.chrome?.webview){reject(Error(T('Bitte die Windows-App starten.','Please launch the Windows app.')));return;}const id=++requestId;pending.set(id,{resolve,reject});window.chrome.webview.postMessage({id,op,...args});});}
window.chrome?.webview?.addEventListener('message',e=>{let d=e.data;if(d.eventName==='progress'){$('progress').value=d.value;$('render-hint').textContent=T('Wird gerendert','Rendering')+' · '+Math.round(d.value*100)+' %';return;}const p=pending.get(d.id);if(p){pending.delete(d.id);d.ok?p.resolve(d.result):p.reject(Error(d.error));}});
function dimensions(){return $('format').value.split('x').map(Number);}
function margins(){return ['top','right','bottom','left'].map(s=>Math.min(40,Math.max(0,Number($('safe-'+s).value)||0)));}
function accent(){return getComputedStyle($('app')).getPropertyValue('--j-accent').trim();}
function formatTime(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');}
function family(){let f=$('font').value;return f.startsWith('asset:')?'Imported'+f.slice(6):f;}
function settings(){return {fields:Object.fromEntries(textIds.map(id=>[id,$(id).value])),video:videoAsset?.id||null,intro,outro,mask:mask?.id||null,segments};}
function remember(){try{localStorage.setItem('veylcut.settings.v1',JSON.stringify(settings()));}catch{notice(T('Einstellungen können in diesem Profil nicht gespeichert werden.','This profile cannot save settings.'),true);}}
function applyFields(data){for(const id of textIds){if(data?.fields&&Object.hasOwn(data.fields,id))$(id).value=String(data.fields[id]);}for(const id of ['safe-top','safe-right','safe-bottom','safe-left'])$(id).value=Math.min(40,Math.max(0,Number($(id).value)||0));}
function setBusy(value,cancellable=false){busy=value;if(value){pause();document.querySelectorAll('button,input,select,textarea,summary').forEach(el=>{if(el.id!=='cancel-render'){el.dataset.wasDisabled=el.disabled?'1':'0';el.disabled=true;}});}else{document.querySelectorAll('[data-was-disabled]').forEach(el=>{el.disabled=el.dataset.wasDisabled==='1';delete el.dataset.wasDisabled;});refreshEnabled();}$('cancel-render').hidden=!value||!cancellable;$('progress').hidden=!value;$('progress').value=0;}
function refreshEnabled(){for(let id of ['plan','play','replace-video','scrub'])$(id).disabled=!videoAsset||busy;for(let id of ['render-preview','export'])$(id).disabled=!engineAvailable||!segments.length||busy;}
const presets=[['none','',T('Ohne Overlay','No overlay')],['signal','signal','Signal'],['frame','frame','Frame'],['minimal','minimal','Minimal']];
function library(kind){const container=$(kind+'-library');container.replaceChildren();for(const [id,style,name] of presets){const button=document.createElement('button');button.className='asset-card';button.setAttribute('aria-pressed',String((kind==='intro'?intro:outro)===id));const thumb=document.createElement('div');thumb.className='asset-thumb '+(style||'none');const label=document.createElement('span');label.className='mini-text';label.textContent=id==='none'?'∅':kind==='intro'?'PRESS PLAY':'NEXT ROUND?';thumb.append(label);const meta=document.createElement('div');meta.className='asset-meta';const title=document.createElement('span');title.textContent=id==='none'?T('Ohne Overlay','No overlay'):name;const type=document.createElement('small');type.textContent=id==='none'?'—':'VECTOR';meta.append(title,type);button.append(thumb,meta);button.onclick=()=>selectOverlay(kind,id);container.append(button);}
 for(const a of media.filter(a=>a.kind===kind)){const b=document.createElement('button');b.className='asset-card';b.setAttribute('aria-pressed',String((kind==='intro'?intro:outro)===a.id));const thumb=document.createElement('div');thumb.className='asset-thumb frame';thumb.textContent=a.duration?T('Eigenes Video','Custom video'):'PNG';const meta=document.createElement('div');meta.className='asset-meta';meta.textContent=a.name;b.append(thumb,meta);b.onclick=()=>selectOverlay(kind,a.id);container.append(b);}}
function selectOverlay(kind,id){if(kind==='intro')intro=id;else outro=id;library(kind);remember();draw();}
async function addMedia(a){if(!a)return;media=media.filter(x=>x.id!==a.id);media.push(a);
 if(a.kind==='music'||a.kind==='sound'){const s=$(a.kind);let opt=[...s.options].find(o=>o.value===a.id);if(!opt){opt=new Option(a.name,a.id);s.append(opt);}}
 if(a.kind==='font'){const face=new FontFace('Imported'+a.id,`url("${a.url}")`);await face.load();document.fonts.add(face);if(![...$('font').options].some(o=>o.value==='asset:'+a.id))$('font').append(new Option(a.name,'asset:'+a.id));}
 if(['intro','outro','mask'].includes(a.kind)){const img=a.duration>0?document.createElement('video'):new Image();img.crossOrigin='anonymous';if(a.duration>0){img.muted=true;img.preload='auto';img.playsInline=true;}img.src=a.url;visuals.set(a.id,img);if(a.kind!=='mask')library(a.kind);}
}
async function choose(kind){if(busy)return;setBusy(true);try{const a=await api('import',{kind});if(!a)return;if(kind==='video')await loadVideo(a);else {await addMedia(a);if(kind==='intro'||kind==='outro')selectOverlay(kind,a.id);if(kind==='music'||kind==='sound')$(kind).value=a.id;if(kind==='font')$('font').value='asset:'+a.id;if(kind==='mask')mask=a;remember();}notice(T('Geladen: ','Loaded: ')+a.name);}catch(e){notice(e.message,true);}finally{setBusy(false);draw();}}
async function loadVideo(a){pause();videoAsset=a;outputTime=0;video.src=a.url;video.load();$('empty').hidden=true;$('file-label').textContent=a.name+' · '+a.width+' × '+a.height+' · '+formatTime(a.duration);await new Promise(resolve=>{const timeout=setTimeout(resolve,5000);video.addEventListener('loadeddata',()=>{clearTimeout(timeout);resolve();},{once:true});video.addEventListener('error',()=>{clearTimeout(timeout);resolve();},{once:true});});makePlan();}
video.addEventListener('error',()=>{if(videoAsset)notice(T('Dieses Quellformat lässt sich nicht direkt abspielen. Nutze „Vorschau rendern“ für Schnitt, Overlays und Ton.','This source format cannot play directly. Use Render preview to see the edit, overlays and sound.'),true);});
function makePlan(){if(!videoAsset)return;pause();const p=core.plan(videoAsset.duration,Number($('length').value),$('prompt').value);segments=p.segments;total=p.duration;outputTime=0;$('scrub').max=total;$('scrub').value=0;const pace={action:T('Schnell','Fast'),calm:T('Ruhig','Calm'),cinematic:'Cinematic',balanced:T('Ausgewogen','Balanced'),uncut:T('Ungeschnitten','Uncut')}[p.pace];$('cut-info').textContent=segments.length+' '+T('Szenen','scenes')+' · '+formatTime(total)+' · '+pace;renderTrack();seek(0);refreshEnabled();remember();}
function renderTrack(){const track=$('cut-track');track.replaceChildren();let cursor=0;segments.forEach((s,i)=>{const b=document.createElement('button');b.className='cut-segment';b.style.flex=String(s.duration);b.textContent=String(i+1).padStart(2,'0')+' / '+formatTime(s.start);b.title=T('Quelle ab ','Source from ')+s.start.toFixed(2)+' s';const t=cursor;b.onclick=()=>{pause();seek(t);};cursor+=s.duration;track.append(b);});}
function seek(t){outputTime=Math.max(0,Math.min(total,t));const loc=core.locate(segments,outputTime);if(loc&&video.readyState>=1)video.currentTime=Math.min(videoAsset.duration-.01,loc.source);$('scrub').value=outputTime;draw();}
function pause(){playing=false;video.pause();$('play').textContent='▶';}
async function play(){if(!videoAsset)return;if(playing){pause();return;}if(video.error){notice(T('Nutze für dieses Quellformat die gerenderte Vorschau.','Use the rendered preview for this source format.'),true);return;}if(outputTime>=total-.05)seek(0);playing=true;lastFrame=performance.now();video.volume=Number($('original-volume').value)/100;try{await video.play();$('play').textContent='Ⅱ';}catch(e){pause();notice(e.message,true);}}
function drawSource(context,w,h){context.fillStyle='#090d10';context.fillRect(0,0,w,h);if(video.readyState<2)return;const ratio=$('fit').value==='cover'?Math.max(w/video.videoWidth,h/video.videoHeight):Math.min(w/video.videoWidth,h/video.videoHeight);const vw=video.videoWidth*ratio,vh=video.videoHeight*ratio;context.drawImage(video,(w-vw)/2,(h-vh)/2,vw,vh);}
function textLines(context,text,maxWidth){const rows=[];for(const paragraph of String(text).split('\n')){let row='';for(const word of paragraph.split(/\s+/)){if(!word)continue;if(context.measureText(word).width>maxWidth){if(row){rows.push(row);row='';}for(const char of word){if(context.measureText(row+char).width>maxWidth){rows.push(row);row='';}row+=char;}}else if(context.measureText(row?row+' '+word:word).width>maxWidth){rows.push(row);row=word;}else row=row?row+' '+word:word;}if(row)rows.push(row);}return rows;}
function drawText(context,text,w,h,position,weight=700){if(!text.trim())return;const r=core.safeRect(w,h,margins()),pad=w*.027;let size=w*(w<h?.066:.043),rows=[];while(size>=5){context.font=`${weight} ${size}px "${family()}"`;rows=textLines(context,text,r.width-pad*2);if(rows.length*size*1.25<=r.height-pad*2)break;size-=1;}const height=rows.length*size*1.25;let y=position==='top'?r.y+pad:position==='bottom'?r.y+r.height-height-pad:r.y+(r.height-height)/2;context.textAlign='center';context.textBaseline='top';context.shadowColor='#000';context.shadowBlur=w*.005;context.shadowOffsetY=w*.002;for(const row of rows){const tw=context.measureText(row).width;context.fillStyle='#081015ce';context.fillRect(r.x+(r.width-tw)/2-size*.24,y-size*.08,tw+size*.48,size*1.18);context.fillStyle='#ffffff';context.fillText(row,r.x+r.width/2,y);y+=size*1.25;}context.shadowBlur=0;context.shadowOffsetY=0;}
function drawPreset(context,id,text,w,h){if(id==='none'||!presets.some(p=>p[0]===id))return;const r=core.safeRect(w,h,margins());context.fillStyle=accent();context.strokeStyle=accent();if(id==='signal'){context.save();context.translate(w*.09,h*.5);context.rotate(.3);context.fillRect(-w*.008,-h*.8,w*.016,h*1.6);context.restore();context.fillRect(w*.84,h*.84,w*.08,h*.008);}else if(id==='frame'){context.lineWidth=Math.max(2,w*.004);context.strokeRect(w*.045,h*.045,w*.91,h*.91);}else context.fillRect(r.x+r.width*.38,r.y+r.height*.66,r.width*.24,h*.006);drawText(context,text,w,h,'center');}
function drawLayer(context,which,w,h,time,exporting=false){if(which==='text'){drawText(context,$('headline').value,w,h,$('text-position').value);return;}const id=which==='intro'?intro:outro,copy=$(which+'-copy').value;
 if(presets.some(p=>p[0]===id))drawPreset(context,id,copy,w,h);else if(!exporting){const asset=media.find(a=>a.id===id),visual=visuals.get(id);if(visual){try{if(visual instanceof HTMLVideoElement){const t=asset.duration?Math.max(0,time%asset.duration):0;if(Math.abs(visual.currentTime-t)>.08)visual.currentTime=t;if(visual.readyState<2)return;}else if(!visual.complete||!visual.naturalWidth)return;const iw=visual.videoWidth||visual.naturalWidth,ih=visual.videoHeight||visual.naturalHeight,scale=Math.min(w/iw,h/ih);context.drawImage(visual,(w-iw*scale)/2,(h-ih*scale)/2,iw*scale,ih*scale);}catch{}}}}
function draw(){const [ow,oh]=dimensions();const w=ow/2,h=oh/2;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}drawSource(ctx,w,h);const edge=Math.min(2,total*.2);if(videoAsset&&total){if(outputTime<=edge)drawLayer(ctx,'intro',w,h,outputTime);else if(outputTime>=total-edge)drawLayer(ctx,'outro',w,h,outputTime-total+edge);else drawLayer(ctx,'text',w,h,outputTime);}
 if(videoAsset&&$('show-safe').checked){const r=core.safeRect(w,h,margins());ctx.fillStyle='#00000055';ctx.fillRect(0,0,w,r.y);ctx.fillRect(0,r.y+r.height,w,h-r.y-r.height);ctx.fillRect(0,r.y,r.x,r.height);ctx.fillRect(r.x+r.width,r.y,w-r.x-r.width,r.height);ctx.strokeStyle='#e1edc170';ctx.lineWidth=1;ctx.setLineDash([5,5]);ctx.strokeRect(r.x,r.y,r.width,r.height);ctx.setLineDash([]);if(mask){const img=visuals.get(mask.id);if(img?.complete&&img.naturalWidth){ctx.globalAlpha=.45;ctx.drawImage(img,0,0,w,h);ctx.globalAlpha=1;}}}
 $('time').textContent=formatTime(outputTime)+' / '+formatTime(total);$('format-badge').textContent=ow===oh?'1:1':ow>oh?'16:9':oh===1920?'9:16':'4:5';const loc=core.locate(segments,outputTime);[...$('cut-track').children].forEach((e,i)=>e.classList.toggle('active',!!loc&&i===loc.index));}
function animate(now){if(playing){const delta=Math.min(.1,(now-lastFrame)/1000);if(!video.seeking&&video.readyState>=2){outputTime=Math.min(total,outputTime+delta);const loc=core.locate(segments,outputTime);if(loc&&Math.abs(video.currentTime-loc.source)>.2)video.currentTime=loc.source;if(outputTime>=total){pause();}else if(video.paused)video.play().catch(()=>pause());$('scrub').value=outputTime;}}lastFrame=now;if(videoAsset)draw();requestAnimationFrame(animate);}
function layers(){const [w,h]=dimensions(),result={};for(const which of ['intro','text','outro']){const c=document.createElement('canvas');c.width=w;c.height=h;drawLayer(c.getContext('2d'),which,w,h,0,true);result[which+'Png']=c.toDataURL('image/png');}return result;}
function request(){const [width,height]=dimensions();return {video:videoAsset.id,width,height,fit:$('fit').value,segments,originalVolume:Number($('original-volume').value)/100,musicVolume:Number($('music-volume').value)/100,soundVolume:Number($('sound-volume').value)/100,music:$('music').value||null,sound:$('sound').value||null,introAsset:presets.some(p=>p[0]===intro)?null:intro,outroAsset:presets.some(p=>p[0]===outro)?null:outro,...layers()};}
async function render(preview){if(!segments.length||busy)return;setBusy(true,true);$('render-hint').textContent=T('Render wird vorbereitet …','Preparing render…');try{const res=await api('render',{preview,request:request()});if(!res)return;if(preview){$('rendered-video').src=res.url;$('render-dialog').showModal();notice(T('Vorschau fertig – inklusive Schnitt, Overlays und Ton.','Preview ready, including cuts, overlays and sound.'));}else{notice(T('MP4 gespeichert: ','MP4 saved: ')+res.path);$('render-hint').textContent=T('Export abgeschlossen.','Export complete.');}}catch(e){notice(e.message,true);$('render-hint').textContent=T('Render beendet. Details in der Meldung.','Render ended. See the message for details.');}finally{setBusy(false);}}
function translate(value){lang=value;document.documentElement.lang=lang;document.querySelectorAll('[data-en]').forEach(e=>{if(!e.dataset.de)e.dataset.de=e.textContent;e.textContent=lang==='en'?e.dataset.en:e.dataset.de;});$('headline').placeholder=T('Dein Moment. Deine Geschichte.','Your moment. Your story.');$('prompt').placeholder=T('Schneller Gameplay-Teaser, knackige Schnitte, 15 Sekunden.','Fast gameplay teaser, punchy cuts, 15 seconds.');library('intro');library('outro');if(videoAsset){$('cut-info').textContent=segments.length+' '+T('Szenen','scenes')+' · '+formatTime(total);$('file-label').textContent=videoAsset.name+' · '+videoAsset.width+' × '+videoAsset.height+' · '+formatTime(videoAsset.duration);}$('engine-state').textContent=engineAvailable?T('Lokal bereit','Local engine ready'):T('FFmpeg fehlt','FFmpeg missing');try{localStorage.setItem('veylcut.language',lang);}catch{}draw();}
async function restoreProject(result){if(!result)return;pause();for(const a of result.assets)await addMedia(a);applyFields(result.settings);intro=result.settings.intro||'none';outro=result.settings.outro||'none';const valid=id=>presets.some(p=>p[0]===id)||media.some(a=>a.id===id);if(!valid(intro))intro='none';if(!valid(outro))outro='none';mask=media.find(a=>a.id===result.settings.mask)||null;const a=result.assets.find(a=>a.id===result.settings.video);if(a){await loadVideo(a);const saved=result.settings.segments;if(Array.isArray(saved)&&saved.length&&saved.every(s=>Number.isFinite(s.start)&&s.start>=0&&Number.isFinite(s.duration)&&s.duration>.1&&s.start+s.duration<=a.duration+.08)){segments=saved;total=segments.reduce((sum,s)=>sum+s.duration,0);$('scrub').max=total;renderTrack();seek(0);}}else{videoAsset=null;segments=[];total=0;video.removeAttribute('src');video.load();$('empty').hidden=false;$('file-label').textContent=T('Quelle fehlt. Bitte Video erneut laden.','Source missing. Load the video again.');renderTrack();}library('intro');library('outro');refreshEnabled();remember();notice(result.missing?T(result.missing+' Quelldatei(en) fehlen. Bitte erneut laden.',result.missing+' source file(s) missing. Please reload.'):T('Projekt geladen.','Project loaded.'),!!result.missing);}
for(const kind of ['intro','outro','music','sound','font','mask'])$(kind+'-import').onclick=()=>choose(kind);
$('video-import').onclick=$('replace-video').onclick=()=>choose('video');
$('demo').onclick=async()=>{setBusy(true);try{await loadVideo(await api('demo'));notice(T('Synthetisches Testvideo geladen.','Synthetic test video loaded.'));}catch(e){notice(e.message,true);}finally{setBusy(false);}};
$('plan').onclick=()=>{const m=$('prompt').value.match(/\b(\d{1,3})\s*(?:s\b|sek|sec)/i);if(m){const n=Math.max(1,Math.min(300,Number(m[1])));if(![...$('length').options].some(o=>Number(o.value)===n))$('length').append(new Option(n+' s',String(n)));$('length').value=String(n);}makePlan();notice(T('Schnitt anhand von Tempo und Ziellänge erstellt. Prüfe die Szenenauswahl in der Vorschau.','Cut created from pace and target length. Review the scene selection in the preview.'));};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{const prompts={action:T('Schneller Gameplay-Teaser, knackige Schnitte.','Fast gameplay teaser, punchy cuts.'),cinematic:T('Cinematic Trailer, epische Momente.','Cinematic trailer, epic moments.'),calm:T('Ruhiger Showcase, lange Einstellungen.','Calm showcase, long shots.')};$('prompt').value=prompts[b.dataset.prompt];remember();});
$('play').onclick=play;$('scrub').oninput=()=>{pause();seek(Number($('scrub').value));};$('render-preview').onclick=()=>render(true);$('export').onclick=()=>render(false);$('cancel-render').onclick=()=>api('cancel').catch(e=>notice(e.message,true));
$('render-close').onclick=()=>{$('rendered-video').pause();$('render-dialog').close();};$('render-dialog').addEventListener('close',()=>$('rendered-video').pause());
$('project-save').onclick=async()=>{try{if(await api('saveProject',{settings:settings()}))notice(T('Projekt gespeichert. Quelldateien bleiben am ursprünglichen Ort.','Project saved. Source files remain in their original location.'));}catch(e){notice(e.message,true);}};
$('project-load').onclick=async()=>{setBusy(true);try{await restoreProject(await api('loadProject'));}catch(e){notice(e.message,true);}finally{setBusy(false);}};
$('mask-clear').onclick=()=>{mask=null;remember();draw();};
$('safe-preset').onchange=()=>{const m={free:[8,8,8,8],reels:[14,14,35,8],tiktok:[12,18,25,8],shorts:[12,18,24,8]}[$('safe-preset').value];if(m)['top','right','bottom','left'].forEach((s,i)=>$('safe-'+s).value=m[i]);remember();draw();};
document.querySelectorAll('.margin').forEach(el=>el.addEventListener('change',()=>{el.value=Math.min(40,Math.max(0,Number(el.value)||0));$('safe-preset').value='custom';remember();}));
textIds.forEach(id=>$(id).addEventListener('input',()=>{remember();draw();}));$('original-volume').addEventListener('input',()=>video.volume=Number($('original-volume').value)/100);$('length').addEventListener('change',makePlan);$('show-safe').onchange=draw;
$('language').onchange=()=>translate($('language').value);
const look=JanoKit.look($('app'),'veylcut.look.v1');
function previewLook(){look.preview({accent:$('accent').value,density:$('density').value});draw();}
function cancelLook(){look.cancel();$('look-dialog').close();draw();}
$('look-open').onclick=()=>{const s=look.current();$('accent').value=s.accent;$('density').value=s.density;$('look-error').textContent='';$('look-dialog').showModal();};
document.querySelectorAll('[data-color]').forEach(b=>{b.style.background=b.dataset.color;b.onclick=()=>{$('accent').value=b.dataset.color;previewLook();};});$('accent').oninput=$('density').onchange=previewLook;
$('look-cancel').onclick=$('look-close').onclick=cancelLook;$('look-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelLook();});$('look-form').onsubmit=e=>{e.preventDefault();const r=look.save({accent:$('accent').value,density:$('density').value});if(r.ok)$('look-dialog').close();else $('look-error').textContent=r.message;draw();};
async function initialize(){try{const data=await api('ready');engineAvailable=data.engine;for(const a of data.library)try{await addMedia(a);}catch(e){notice(a.name+': '+e.message,true);}try{const saved=JSON.parse(localStorage.getItem('veylcut.settings.v1'));applyFields(saved);if(saved){intro=presets.some(p=>p[0]===saved.intro)||media.some(a=>a.id===saved.intro)?saved.intro:'signal';outro=presets.some(p=>p[0]===saved.outro)||media.some(a=>a.id===saved.outro)?saved.outro:'frame';mask=media.find(a=>a.id===saved.mask)||null;}}catch{}if(!engineAvailable)notice(T('FFmpeg wurde nicht gefunden. Bitte FFmpeg installieren und die App neu starten.','FFmpeg was not found. Install FFmpeg and restart the app.'),true);}catch(e){notice(e.message,true);}try{lang=localStorage.getItem('veylcut.language')||'de';}catch{}$('language').value=lang;translate(lang);$('engine-state').dataset.tone=engineAvailable?'success':'warning';refreshEnabled();window.appReady=true;}
window.runSelfTest=async function(){
 const checks=[];function expect(value,label){if(!value)throw Error(label);checks.push(label);}
 expect(engineAvailable,'Local FFmpeg detected');
 $('length').value='6';$('prompt').value='Schneller Gameplay Teaser';$('headline').value='DEIN NÄCHSTER\nGROSSER MOMENT';
 await loadVideo(await api('demo'));await new Promise(r=>setTimeout(r,350));if(video.readyState<2){let debug={};try{const f=await fetch(video.src);const bytes=await f.arrayBuffer();debug={status:f.status,type:f.headers.get('content-type'),size:bytes.byteLength,head:[...new Uint8Array(bytes.slice(0,32))],support:video.canPlayType('video/mp4; codecs="avc1.42E01E"')};}catch(e){debug={fetchError:e.message};}expect(false,'Video decoding: '+JSON.stringify({ready:video.readyState,error:video.error?.message,debug}));}expect(segments.length>1&&Math.abs(total-6)<.01,'Rule-based edit with multiple excerpts');
 $('format').value='1080x1920';$('safe-preset').value='tiktok';$('safe-preset').dispatchEvent(new Event('change'));draw();
 const rect=core.safeRect(1080,1920,margins());expect(rect.x>0&&rect.width<1080&&rect.height<1920,'Editable safe area');
 const savedText=$('headline').value;translate('en');expect($('headline').value===savedText&&$('project-save').textContent==='Save project','Language retains content');translate('de');
 const before=accent();$('look-open').click();$('accent').value='#ef8cae';previewLook();cancelLook();expect(accent()===before,'Look cancel restores accent');
 await api('saveProject',{settings:settings()});const loaded=await api('loadProject');expect(loaded.settings.fields.headline===savedText&&loaded.assets.length>0,'Project save and load');
 const range=await fetch(video.src,{headers:{Range:'bytes=0-15'}});expect(range.status===206&&(await range.arrayBuffer()).byteLength===16,'Bounded local media range request');
 let preview=await api('render',{preview:true,request:request()});expect(preview.duration>5.8&&preview.width===360&&preview.height===640,'Real preview: portrait, duration, compositing');
 const player=$('rendered-video');await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Rendered preview loading timeout')),10000);player.onloadeddata=()=>{clearTimeout(timeout);resolve();};player.onerror=()=>{clearTimeout(timeout);reject(Error('Rendered preview decoding failed'));};player.src=preview.url;player.load();});expect(player.readyState>=2,'Rendered preview plays in the app');
 $('format').value='1920x1080';$('safe-preset').value='free';$('safe-preset').dispatchEvent(new Event('change'));
 const exported=await api('render',{preview:false,request:request()});expect(exported.path.endsWith('.mp4'),'Real full-resolution MP4 export');
 await new Promise(resolve=>{video.addEventListener('seeked',resolve,{once:true});seek(total*.5);setTimeout(resolve,3000);});draw();expect(video.readyState>=2,'Seeked working preview decoded');
 $('render-hint').textContent='Vorschau und MP4-Export geprüft.';
 expect(document.documentElement.scrollWidth<=innerWidth,'No horizontal overflow');
 notice('Selbsttest bestanden · echter MP4-Export und Vorschau geprüft.');return checks;
};
requestAnimationFrame(animate);initialize();

// Native chrome revision 2026-09-21 supplies the persistent creator link.
(()=>{if(!window.chrome?.webview)return;const hide=()=>document.querySelectorAll('a').forEach(a=>{if(a.textContent.trim().toLowerCase()==='created by jona fynn schlegelmilch')a.style.display='none';});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hide,{once:true});else hide();})();
